### ISSUE TITLE
test "test_dump_load" failing 

### ISSUE THREAD

**Issue by realnitinworks** [piccolo-orm/piccolo#377]
I followed the "Get the tests running" steps in https://piccolo-api.readthedocs.io/en/latest/contributing/index.html. All steps work fine and I ran the ./scripts/test-postgres.sh. One test fails

`FAILED tests/apps/fixtures/commands/test_dump_load.py::TestDumpLoad::test_dump_load - AssertionError: {'id'[261 chars]('1.10'),`

```
>   self.assertDictEqual(
            mega_table_data[0],
            {
                "id": 1,
                "bigint_col": 1,
                "boolean_col": True,
                "bytea_col": b"hello",
                "date_col": datetime.date(2021, 1, 1),
                "foreignkey_col": 1,
                "integer_col": 1,
                "interval_col": datetime.timedelta(seconds=10),
                "json_col": '{"a":1}',
                "jsonb_col": '{"a":1}',
                "numeric_col": decimal.Decimal("1.1"),
                "real_col": 1.1,
                "double_precision_col": 1.344,
                "smallint_col": 1,
                "text_col": "hello",
                "timestamp_col": datetime.datetime(2021, 1, 1, 0, 0),
                "timestamptz_col": datetime.datetime(
                    2021, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                ),
                "uuid_col": uuid.UUID("12783854-c012-4c15-8183-8eecb46f2c4e"),
                "varchar_col": "hello",
                "unique_col": "hello",
                "null_col": None,
                "not_null_col": "hello",
            },
        )
E       AssertionError: {'id'[261 chars]('1.10'), 'real_col': 1.1, 'double_precision_c[338 chars]llo'} != {'id'[261 chars]('1.1'), 'real_col': 1.1, 'double_precision_co[333 chars]llo'}
E       Diff is 992 characters long. Set self.maxDiff to None to see it.

tests/apps/fixtures/commands/test_dump_load.py:105: AssertionError
```

A note on how I setup Postgres: I spun up the Postgres using docker using the docker-compose file:

```
version: '3.8'

services:
  postgres-db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=piccolo

volumes: 
  postgres_data:
```

and then before running the tests I exported the following environment variables like so:

```
export PG_USER=postgres
export PG_PASSWORD=postgres
export PG_DATABASE=piccolo
```

Are the tests really failing or is it something to do with my setup for piccolo development?
